### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by jducnuigeen** [BuntingLabs/buntinglabs-qgis-plugin#3]
On Ubuntu 22.04, and QGIS 3.28.15, I get an error when pressing the icon to start using the tool:

2024-02-07T15:21:36     WARNING    Traceback (most recent call last):
              File "/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins/buntinglabs-qgis-plugin/plugin.py", line 503, in toolbarClick
              self.openTOSDialog()
              File "/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins/buntinglabs-qgis-plugin/plugin.py", line 147, in openTOSDialog
              layout.addWidget(OnboardingHeaderWidget([
              File "/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins/buntinglabs-qgis-plugin/onboarding_widget.py", line 22, in __init__
              step_widget = StepWidget(step, i == active_step)
              File "/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins/buntinglabs-qgis-plugin/onboarding_widget.py", line 44, in __init__
              font.setPointSize(font.pointSize() * 1.25) # Upgrade font size by 1.4x
             TypeError: setPointSize(self, int): argument 1 has unexpected type 'float'

I was never asked to insert my secret setup code from my email registration, so maybe this is related?

**Comment by brendanashworth** [comment]
Thanks @jducnuigeen , this is definitely not your fault, I think I'm using the wrong function to set the font size (and it happened to error on yours). I should be using [setPointSizeF](https://doc.qt.io/qt-6/qfont.html#setPointSizeF)

Let me fix this and make a new release — will ping you once that's done!

**Comment by johnwbryant** [comment]
I'm getting the same error as Jan, also on Ubuntu 22.04 (but on QGIS 3.34.3).

Thanks!

**Comment by brendanashworth** [comment]
Thanks @johnwbryant and @jducnuigeen , I just uploaded 1.8 to the QGIS plugin repository which should fix this issue, hoping it gets approved in ~12 hours!

**Comment by johnwbryant** [comment]
Thank you!

**Comment by brendanashworth** [comment]
1.8 is now available on the QGIS plugin repository, let me know if this still pops up!
